# https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows#schedule

name: periodic-markdown-link-check

on:
  schedule:
    - cron: '30 4 * * *'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Markdown links check
        uses: ruzickap/action-my-markdown-link-checker@v1